project:
  type: website
  output-dir: docs

website:
  title: "visual-phrase-structure"

format:
  html:
    code-fold: true
    downloads: [pdf]
    css: styles.css
    toc: true

execute:
  warning: false
  message: false
  echo: false

editor: visual

